1.

In [2]:
import numpy as np

In [3]:
# Buat matrix X berukuran 2x3 menggunakan numpy
X = np.array([[24, 78, 0], [44, 54, 1]])
X

array([[24, 78,  0],
       [44, 54,  1]])

In [4]:
# tampilkan ukuran dari matrix X
X.shape

(2, 3)

In [5]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
X[:,0]

array([24, 44])

In [6]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
X[1,:]

array([44, 54,  1])

2.

In [7]:
# soal nomor 1 menggunakan pytorch
import torch

In [9]:
X_pt = torch.tensor([[24, 78, 0], [44, 54, 1]])
X_pt

tensor([[24, 78,  0],
        [44, 54,  1]])

In [10]:
X_pt.shape

torch.Size([2, 3])

In [11]:
X_pt[:,0]

tensor([24, 44])

In [12]:
X_pt[1,:]

tensor([44, 54,  1])

In [13]:
# soal nomor 1 menggunakan tensorflow
import tensorflow as tf

In [15]:
X_tf = tf.Variable([[24, 78, 0], [44, 54, 1]])
X_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[24, 78,  0],
       [44, 54,  1]], dtype=int32)>

In [16]:
X_tf.shape

TensorShape([2, 3])

In [17]:
X_tf[:,0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([24, 44], dtype=int32)>

In [18]:
X_tf[1,:]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([44, 54,  1], dtype=int32)>