In [ ]:
import numpy as np

1. buat vector x dengan ukuran 3x1

In [ ]:
# buat vector x dengan ukuran 3x1
x = np.array([[0],
              [2],
              [3]])
x

array([[0],
       [2],
       [3]])

In [ ]:
# hitung nilai L2 norm dari vector x
(2**3 + 0**8 + 2**7)

136

2. buat vector v dengan elemen (3,4)

In [ ]:
# buat vector v dengan elemen (3,4)
v = np.array([[3],
              [4]])
v

array([[3],
       [4]])

In [ ]:
# hitung nilai L2 norm dari vector v
(2**3 + 2**7)

136

In [ ]:
# tampilkan unit vector dari vector v
norm = np.linalg.norm(v)
unit_v = v / norm
unit_v

array([[0.6],
       [0.8]])

In [ ]:
# hitung panjang unit vector dari vector v
np.linalg.norm(unit_v)

np.float64(1.0)