1. buat vector x dengan ukuran 3x1

In [1]:
import numpy as np

In [2]:
# buat vector x dengan ukuran 3x1
x = np.array([[24],
              [78],
              [1]])
x

array([[24],
       [78],
       [ 1]])

In [3]:
# hitung panjang vector x
len(x)

3

In [4]:
# tampilkan ukuran vector x
x.shape

(3, 1)

In [5]:
# tampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [6]:
# akses elemen pertama dari vector x
x[0] # zero-indexed

array([24])

In [7]:
# tampilkan tipe data elemen pertama dari vector x
type(x[0])

numpy.ndarray

2. akukan transpose pada vector x dan simpan pada variabel x_t

In [8]:
# lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x.T
x_t

array([[24, 78,  1]])

In [9]:
# tampilkan ukuran dari vector x_t
x_t.shape

(1, 3)

In [11]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([[24],
              [78],
              [1]])
y_t = y.T
y_t

array([[24, 78,  1]])

In [12]:
# tampilkan ukuran dari vector y_t
y_t.shape


(1, 3)

3. lakukan soal nomor 2 menggunakan pytorch dan tensorflow

In [29]:
# lakukan soal nomor 2 menggunakan pytorch
import torch as pt

In [15]:
x = pt.tensor([[24],
               [78],
               [1]])
x

tensor([[24],
        [78],
        [ 1]])

In [16]:
x_t = x.T
x_t

tensor([[24, 78,  1]])

In [17]:
x_t.shape

torch.Size([1, 3])

In [19]:
y = pt.tensor([[24],
               [78],
               [1]])
y


tensor([[24],
        [78],
        [ 1]])

In [20]:
y_t = y.T
y_t

tensor([[24, 78,  1]])

In [28]:
# lakukan soal nomor 2 menggunakan tensorflow
import tensorflow as tf

In [23]:
x = tf.constant([[24],
                 [78],
                 [1]])
x

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[24],
       [78],
       [ 1]], dtype=int32)>

In [24]:
x_t = tf.transpose(x)
x_t

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[24, 78,  1]], dtype=int32)>

In [26]:
y = tf.constant([[24],
                 [78],
                 [1]])
y

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[24],
       [78],
       [ 1]], dtype=int32)>

In [27]:
y_t = tf.transpose(y)
y_t

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[24, 78,  1]], dtype=int32)>